### ISSUE TITLE
PR to support s6/s6-rc?

### ISSUE THREAD

**Issue by tomeon** [svanderburg/nix-processmgmt#1]
Hi @svanderburg -- I'm wondering if you would consider a PR to support the [s6 process supervision suite](https://skarnet.org/software/s6/) and its sibling project the [s6-rc service manager](https://www.skarnet.org/software/s6-rc/)?  TYVM!

**Comment by svanderburg** [comment]
It would definitely be nice to extend the approach to other process managers as well and see how well the process agnostic model works. Furthermore, I think s6 also has unique properties to offer next to the process managers that I have currently tested.

I'm not against accepting any PRs, but keep in mind that this repository is still in an early prototyping stage -- the structure, conventions and function interfaces are not stable and may get overhauled. Basically, with this research project I intend to achieve four major goals, and I only have accomplished just two them, so I'm still only halfway.

When I'm done exploring these milestones, I'm going to think about what to do with my lessons learned. Maybe we can integrate this into Nixpkgs/NixOS, adapt/ajust existing Nixpkgs/NixOS concepts or perhaps we can make another sub project that is open for community contributions.

**Comment by bqv** [comment]
Keeping an eye on this! I'd also love to see s6 here.

**Comment by Kokokokoka** [comment]
This would be marvelous!

**Comment by bqv** [comment]
I've been idly working on a shim layer to convert nixpkgs to an s6 initsystem. I'd have loved to use this instead but I'd want either runit or s6, and it'd be even more work to rework it all.. not to mention my code's a shipwreck, even if it just about works

**Comment by svanderburg** [comment]
I have started working on an `s6-rc` backend. Work in progress branch here: https://github.com/svanderburg/nix-processmgmt/tree/s6-rc

What is already supported:
* Function abstractions to generate a `longrun`, `oneshot` and `bundle` service. Handy abstraction function to automatically generate a log companion service for a `longrun` service.
* A generator function that maps the high level `createManagedProcess` config to a `longrun` (for foreground processes) or `oneshot` service (for traditional daemons)
* Works for the simple webapps + nginx reverse proxy example

**Comment by bqv** [comment]
You're amazing, thank you!

**Comment by svanderburg** [comment]
I just made a pull request for updating s6 and all other skaware packages: https://github.com/NixOS/nixpkgs/pull/110381

I have commit access, but since I consider myself still a newbie to s6 and I don't use it for any production systems, I have decided to take the official route and ask for a review.

Maybe you can take a look at it as well and see if I did not break anything by accident.

**Comment by svanderburg** [comment]
I'm closing this issue, because the above branch was merged into master and the functionality is (somewhat) usable.

What is possible now:
* Launch `s6-svcan` as a service, not as PID 1. It can be used as a replacement for `supervisord`. The `nixproc-s6-rc-switch` tool can be used to deploy a configuration that is managed by `s6-svscan`.
* Constructing a multi-process container in which all services are supervised with `s6-svscan` and managed with `s6-rc`.

Although `s6-rc` is now another backend option, keep in mind that this framework is still highly experimental and not yet ready for production usage.
